import { readdirSync, rmSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { defineConfig } from 'wxt';

function removeRedundantWasm(dir: string): void {
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return;
  }
  for (const entry of entries) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      removeRedundantWasm(full);
    } else if (/[/\\]assets[/\\]ort-wasm-.*\.wasm$/.test(full)) {
      rmSync(full);
      console.log(`ℹ Removed redundant bundled copy: ${entry}`);
    }
  }
}

export default defineConfig({
  hooks: {
    // WXT derives action.default_title from the popup's, which would
    // override our value, so set the localized tooltip after the manifest is
    // generated. The __MSG_*__ tokens resolve from _locales/*/messages.json.
    'build:manifestGenerated'(_wxt, manifest) {
      manifest.action = { ...manifest.action, default_title: '__MSG_actionTitle__' };
    },
    'build:done'(wxt) {
      // Dev rebuilds must keep bundled WASM reachable; strip duplicates on release only.
      if (wxt.config.command === 'serve') {
        return;
      }
      removeRedundantWasm(wxt.config.outDir);
    },
  },
  manifest: {
    // "Tabby" is a brand name, so it stays the same in every language.
    // The description and toolbar tooltip are localized via _locales/*/messages.json
    // (generated by scripts/generate-locales.mjs). default_locale is the fallback.
    name: 'Tabby',
    short_name: 'Tabby',
    default_locale: 'en',
    description: '__MSG_extDescription__',
    permissions: ['tabs', 'storage', 'alarms', 'scripting', 'offscreen'],
    host_permissions: ['<all_urls>'],
    action: {
      default_title: '__MSG_actionTitle__',
    },
    web_accessible_resources: [
      {
        resources: ['sprites/*/*.png'],
        matches: ['<all_urls>'],
      },
    ],
    content_security_policy: {
      extension_pages:
        "script-src 'self' 'wasm-unsafe-eval'; object-src 'self'",
    },
  },
  zip: {
    name: 'tabby',
  },
  webExt: {
    startUrls: ['https://www.google.com'],
  },
  dev: {
    reloadCommand: 'Alt+R',
  },
});
