import { readdirSync, rmSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { defineConfig } from 'wxt';

const FORBIDDEN_OUTPUT_DIRS = ['sprites', 'models', 'ort', '_metadata', '__MACOSX'];
const FORBIDDEN_OUTPUT_FILES = ['.DS_Store'];

function removeForbiddenDirs(dir: string, prefix = ''): void {
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return;
  }
  for (const entry of entries) {
    const rel = prefix ? `${prefix}/${entry}` : entry;
    const full = join(dir, entry);
    if (FORBIDDEN_OUTPUT_DIRS.includes(entry) && statSync(full).isDirectory()) {
      rmSync(full, { recursive: true, force: true });
      console.log(`ℹ Removed ${rel}/ from build output`);
      continue;
    }
    if (FORBIDDEN_OUTPUT_FILES.includes(entry) && statSync(full).isFile()) {
      rmSync(full, { force: true });
      console.log(`ℹ Removed ${rel} from build output`);
      continue;
    }
    if (entry.startsWith('._') && statSync(full).isFile()) {
      rmSync(full, { force: true });
      console.log(`ℹ Removed ${rel} from build output`);
      continue;
    }
    if (statSync(full).isDirectory()) {
      removeForbiddenDirs(full, rel);
    }
  }
}

export default defineConfig({
  hooks: {
    // WXT derives action.default_title from the popup's, which would
    // override our value, so set the localized tooltip after the manifest is
    // generated. The __MSG_*__ tokens resolve from _locales/*/messages.json.
    'build:manifestGenerated'(_wxt, manifest) {
      manifest.action = { ...manifest.action, default_title: '__MSG_actionTitle__' };
    },
    'build:done'(wxt) {
      if (wxt.config.command === 'serve') {
        return;
      }
      removeForbiddenDirs(wxt.config.outDir);
    },
  },
  manifest: {
    // "Tabby" is a brand name, so it stays the same in every language.
    // The description and toolbar tooltip are localized via _locales/*/messages.json
    // (generated by scripts/generate-locales.mjs). default_locale is the fallback.
    name: 'Tabby',
    short_name: 'Tabby',
    default_locale: 'en',
    description: '__MSG_extDescription__',
    permissions: ['tabs', 'storage', 'alarms', 'scripting'],
    // No host_permissions — the content script is declared in the manifest (see
    // entrypoints/content). That covers the floating cat on normal navigation
    // without broad host_permissions (Chrome Web Store).
    action: {
      default_title: '__MSG_actionTitle__',
    },
    web_accessible_resources: [
      {
        resources: ['gif/*/*.gif'],
        matches: ['<all_urls>'],
      },
    ],
    content_security_policy: {
      extension_pages: "script-src 'self'; object-src 'self'",
    },
  },
  zip: {
    name: 'tabby',
    exclude: ['_metadata/**', '__MACOSX/**', '**/.DS_Store', '**/._*'],
  },
  webExt: {
    startUrls: ['https://www.google.com'],
  },
  dev: {
    reloadCommand: 'Alt+R',
  },
});
