/** Middle East and Africa banks. */
export const MIDDLE_EAST_AFRICA_BANK_HOST_ROOTS: readonly string[] = [
  'emiratesnbd.com',
  'adcb.com',
  'alrajhibank.com.sa',
  'snb.com.sa',
  'riyadbank.com',
  'qnb.com',
  'fab.ae',
  'mashreqbank.com',
  'stanbicbank.com',
  'standardbank.co.za',
  'absa.co.za',
  'fnb.co.za',
  'nedbank.co.za',
  'capitecbank.co.za',
  'ecobank.com',
  'gtbank.com',
  'accessbankplc.com',
  'zenithbank.com',
  'attijariwafabank.com',
  'cihbank.ma',
  'banquemisr.com',
  'nbe.com.eg',
];
