/** East, South, and Southeast Asia streaming services. */
export const STREAMING_ASIA_HOST_ROOTS: readonly string[] = [
  'viu.com',
  'sonyliv.com',
  'zee5.com',
  'jiocinema.com',
  'voot.com',
  'u-next.jp',
  'abema.tv',
  'tver.jp',
  'paravi.jp',
  'fod.fujitv.co.jp',
  'unext.jp',
  'wavve.com',
  'tving.com',
  'coupangplay.com',
  'iwanttfc.com',
  'iqiyi.com',
  'youku.com',
  'mgtv.com',
  'bilibili.tv',
  'dimsum.my',
  'trueid.net',
  'wetv.io',
  'linetv.tw',
  'friDay.tw',
  'catchplay.com',
];
